version: '3.8'

networks:
  cassandra-network:
    driver: bridge
  kafka-network:
    driver: bridge
  redis-network:
    driver: bridge

services:

  #
  # cassandra cluster
  #

  cassandra1:
    image: cassandra:4.0
    restart: always
    hostname: cassandra1
    networks:
      - cassandra-network
    ports:
      - 9041:9042
    environment:
      environment:
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
      CASSANDRA_CLUSTER_NAME: report-phone-cassandra-cluster
      CASSANDRA_SEEDS: cassandra1

  #
  # redis
  #

  redis:
    image: redis:6.0.9-alpine
    restart: always
    hostname: redis
    networks:
      - redis-network
    ports:
      - 6379:6379

  #
  #  zookeeper cluster
  #

  zoo1:
    image: zookeeper:3.6.2
    restart: always
    hostname: zoo1
    networks:
      - kafka-network
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_STANDALONE_ENABLED: "true"

  #
  # kafka cluster
  #

  kafka1:
    image: bitnami/kafka:2.6.0
    restart: always
    hostname: kafka1
    networks:
      - kafka-network
    ports:
      - 9081:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://docker-host:9081
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
    depends_on:
      - zoo1

  #
  # schemaregistry
  #

  schemaregistry1:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schemaregistry1
    networks:
      - kafka-network
    ports:
      - 8091:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry1
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
    depends_on:
      - kafka1

  #
  # rest proxy
  #

  restproxy:
    image: confluentinc/cp-kafka-rest:5.4.3
    restart: always
    hostname: restproxy
    networks:
      - kafka-network
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_HOST_NAME: restproxy
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
    depends_on:
      - kafka1

  #
  # kafka manager
  #

  kafkamanager:
    image: kafkamanager/kafka-manager:3.0.0.4
    hostname: kafkamanager
    networks:
      - kafka-network
    ports:
      - 8083:9000
    environment:
      ZK_HOSTS: zoo1:2181
    depends_on:
      - zoo1
      - kafka1